lab_programming = int(input("Enter the number of assignments completed: ")
quizzes_or_in_class_activities = int(input("Enter the number of quizzes completed: "))
assignment_1 = int(input("Enter grade for Assignment 1: "))
assignment_2 = int(input("Enter grade for Assignment 2: "))
assignment_3 = int(input("Enter grade for Assignment 3: "))
assignment_4 = int(input("Enter grade for Assignment 4: "))
